name: gnn_solv_screen
channels:
  - defaults
dependencies:
  - pip
  - python=3.10.18
  - pip:
      - mordred==1.2.0
      - pandas==2.3.0
      - rdkit==2025.3.3
      - torch
      - pyg_lib
      - torch-cluster
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - torch-spline-conv
      - tqdm==4.67.1

