name: gnn_solv_screen
channels:
  - defaults
dependencies:
  - pip
  - python=3.10.18
  - pip:
      - mordred==1.2.0
      - pandas==2.3.0
      - rdkit==2025.3.3
      - torch==2.7.1+cpu
      - pyg_lib
      - torch-cluster==1.6.3+pt27cpu
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt27cpu
      - torch-sparse==0.6.18+pt27cpu
      - torch-spline-conv==1.2.2+pt27cpu
      - tqdm==4.67.1

