name: Reproducibility Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: GEGNN
        environment-file: environment.yml
        python-version: 3.10.13
        auto-activate-base: false
        verbose: true

    - name: Check Python version
      run: python --version

    - name: Run your script
      run: python src/solvent_screening/01_screening.py --metric custom_inf
