name: Reproducibility Check

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Miniconda and create environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: gnn_solv_screen
        environment-file: environment.yml
        python-version: 3.10
        auto-activate-base: false
        auto-update-conda: true

    - name: Show conda info (debugging)
      shell: bash -l {0}
      run: |
        conda info
        conda env list

    - name: Confirm Python version
      shell: bash -l {0}
      run: python --version

    - name: Run main script
      shell: bash -l {0}
      run: python src/solvent_screening/01_screening.py --metric custom_inf
