name: Reproducibility Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install PyTorch and torch-scatter first (CPU version)
      run: |
        pip install torch==2.7.1 --index-url https://download.pytorch.org/whl/cpu
        pip install torch-scatter==2.1.2 -f https://data.pyg.org/whl/torch-2.7.1+cpu.html

    - name: Install remaining dependencies
      run: |
        pip install -r requirements-ci.txt

    - name: Run reproducibility check
      run: |
        python src/solvent_screening/01_screening.py --metric custom_inf

